### ISSUE TITLE
Serving from sub-path

### ISSUE THREAD

**Issue by mo-rijndael** [cmd410/noire#2]
So Noire will be able to be served not only from root of (sub)domain, but from places like /blog/ or /notes/
To achieve this, two things have to be done:
- [ ] Generate relative links where possible
- [ ] Generate links with user-defined base url, when not

**Comment by cmd410** [comment]
Serving application from a sub path is as easy as changing directory structure to be something like this:
```
$NOIRE_DATA_DIR
    cache
        ...
    posts
        your-subpath-direcotries-here
            css
                ...
            favicon.ico
            [...your posts and whatever else...]
```
This works because noire first looks into posts directory when it looks for files, only then fallbacks to static directory.
Then just configure nginx to proxy only `your-subpath-direcotries-here` location to noire.
